# Generated by Django 5.2.7 on 2025-10-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_artist_musicgenre_remove_track_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
