# Generated by Django 5.2.7 on 2025-10-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='formed_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
