# Generated by Django 5.2.7 on 2025-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicGenre',
            new_name='Genre',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genres',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='albums', to='music.genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.IntegerField(help_text='Duration in seconds'),
        ),
    ]
